### ISSUE TITLE
Have storage node check/enforce upload limits

### ISSUE THREAD

**Issue by bwhm** [Joystream/storage-node-joystream#14]
There will a variety of restrictions on uploads on the final platform. Some basic limits should be applied already.

Must:
`max_file_size` = 100MB
`accepted_extensions` = ???
Nice to haves:
`max_video_length` = 10min
`max_audio_length` = 100min

Global/membership restrictions pr n blocks etc can wait.

**Comment by jfinkhaeuser** [comment]
Relates to #5 and #8

**Comment by jfinkhaeuser** [comment]
Also Joystream/substrate-runtime-joystream#21

**Comment by jfinkhaeuser** [comment]
The issue with accepted file extensions isn't so much that it's possible to limit things here. The issue is that under adversarial conditions, you'd have to parse the data to ensure it's actually legitimate. Since streaming formats are container formats that can contain just about anything, that's arbitrarily complex.

We can, of course, stick to limiting what the client advertises as the `Content-Type`, and that's simple enough to implement. But it must be understood that this is a low hurdle to pass.

Independently of this issue, the set of accepted file types *for each purpose* is important. For avatars, `video/*` makes no sense, but for podcasts `image/*` doesn't. There is no notion of this anywhere.

So for Athens, I would propose only limiting size, then following something along the lines of Joystream/substrate-runtime-joystream/issues/21 post-Athens.

**Comment by bwhm** [comment]
I was actually not thinking the latter would be to avoid someone _trying_ to upload an unwanted extension by obfuscation. My thought was the following upload process:

1. Users have to input `extension`, `length` and `file_size` as metadata in [apps](https://github.com/Joystream/apps) (and CLI here if we get that ready). 
2. If they choose a number/ext outside of valid range, the upload is not initiated. 
3. If inside the range, the upload would start.
4. If upload is not complete when `uploaded_data` = `file_size`, the upload is aborted.
5. At completion, the receiving `storage node` would parse the data
6. Only if the actual matches the metadata would it be allowed in the content directory and shared with the other storage nodes.

I am sure this is not a perfect, but it would avoid 1. unintentional mistakes and 2. low effort attempts.

**Comment by jfinkhaeuser** [comment]
Well, extensions are particularly bad for determining file types, but yes, that's sort of what I mean as something we can do fairly easily. Also with regards to upload sizes, we can do your point 4.

I think for Athens we're on the same page, just wanted to ensure people don't expect any kind of guarantee from this :)

**Comment by jfinkhaeuser** [comment]
We'd want to use e.g. https://www.npmjs.com/package/file-type for file type detection for what it's worth. It's also no guarantee, but it's at least looking at the file header.
