### ISSUE TITLE
Insufficient rewards?

### ISSUE THREAD

**Issue by bwhm** [Joystream/storage-node-joystream#92]
It appears the `Storage Providers` are not getting enough rewards to cover the transaction costs, and thus expire.

It happened to our own node recently, and the node that is currently has 3001Joy.

Will transfer funds to the account and see if it announces by itself.

**Comment by bwhm** [comment]
After cross checking `helios` with the balances of expired providers, I'm confident this is the case.

I think you've highlighted this is a potential issue before, but I think it's now becoming a problem. Although we are compensating the `storage providers`, we can't expect them to pay attention to their balances without a warning/grace period.

I'll send each `actor` 1k for now, then we can discuss further when you're back.

Can we change the reward from 10Joy/600blocks via a `sudo` extrinsic, or does it require a runtime upgrade before we release the new actors module?

If the latter, we can have another council vote!

**Comment by bwhm** [comment]
After transferring 1k to each provider, none has expired.

The funds are slowly getting drained though.

**Comment by mnaamani** [comment]
Thats a bit concerning. The locks on the accounts (with exception of our node) should only restrict spending for "Transfer", "Reserve" (if amount goes below the 3000 tokens) Funds should be still spendable to pay for Fees and TransactionPayment. You observation clearly indicates otherwise.
I will have to review the LockableCurrency docs/implementation to see what is going wrong either with my understanding or our implementation.

**Comment by mnaamani** [comment]
So I unstaked and restaked the joystream node to get the account lock to be same as all other members. It is behaving as expected, the node is able to send transactions and pay the fees from the "locked" stake.  

![Screen Shot 2019-08-06 at 6 46 21 PM](https://user-images.githubusercontent.com/1621012/62555016-dcb6d000-b87a-11e9-8173-23a561a1dae1.png)

So at least the problem is not as described as far as I can tell. 

I still think the reward is too little of course but it will only be a problem when we see balance of the accounts approach zero.

**Comment by bwhm** [comment]
Good to know!

I should only have sent the 1k to a subset of the actors, so we could have seen how they behaved.

Is there a chance it means they're not running latest master?

**Comment by mnaamani** [comment]
Yes it is a possibility that they are not running latest master.
One way to try to find out is to try to `ipfs ping` their identity. 

![Screen Shot 2019-08-08 at 5 45 02 PM](https://user-images.githubusercontent.com/1621012/62712840-4c0bfb80-ba04-11e9-84f6-f71cc8a85f24.png)

```
ipfs ping QmSV83mZkvQj48VT6QRKguroBz6sgzxMEcwYrS7k25sZf6
Looking up peer QmSV83mZkvQj48VT6QRKguroBz6sgzxMEcwYrS7k25sZf6
PING QmSV83mZkvQj48VT6QRKguroBz6sgzxMEcwYrS7k25sZf6.
Pong received: time=218.66 ms
Pong received: time=432.67 ms
Pong received: time=96.98 ms
Pong received: time=90.26 ms
```

It might be a good idea to add an `ipfs ping` test in helio

**Comment by mnaamani** [comment]
Older versions will not respond because they don't use the ipfs node identity
